@startsalt
title Екран налаштувань

{+
  <b>Налаштування сповіщень</b>
  ==
  {
    { Оберіть приміщення: | ^Кухня^}
    --
    Встановіть температурні пороги для <b>'Кухня'</b>:
    { Нижній поріг, °C: | "5" }
    { Верхній поріг, °C: | "40" }
    --
    { Моніторинг: | [X] "Увімкнено" }

  }
  --
  {
    {
      [ Зберегти <&save> ]
    }
  }
}
@endsalt
