@startsalt
title Модальне вікно сповіщення

{+
  "⚠️  <b>Попередження системи</b>"
  ==
  {

    Зафіксовано критичну температуру!
    Приміщення: <b>Кухня</b>
    Поточне значення: <color:red><b>45°C</b></color> (Поріг: 40°C)

  }
  --
  {
    {
      [ OK <&check> ]
    }
  }
}
@endsalt
