@startsalt
title Інтерактивний екран моніторингу

{+
  <b>Панель моніторингу</b>
  ==
 {
    Приміщення: <b>Кухня</b>
    Температура: <size:16><b>22°C</b></size>
    Статус: <b>Моніторинг увімкнено</b>
    {
      {
        [ <&cog> Налаштувати ]
      }
    }
    --
    Приміщення: <b>Спальня</b>
    Температура: <size:16><b>20°C</b></size>
    Статус: Моніторинг вимкнено
    {
      {
        [ <&cog> Налаштувати ]
      }
    }
  }
}
@endsalt
