@startuml
title Реляційна модель системи моніторингу

hide circle

entity "Користувач" as user {
  (PK) user_id : INTEGER 
  --
  ім’я : VARCHAR(50)
  прізвище : VARCHAR(50)
  електронна_адреса : VARCHAR(100)
  номер_телефону : VARCHAR(20)
  останній_вхід : TIMESTAMP
}

entity "Моніторинг" as monitoring {
  (PK) monitoring_id : INTEGER
  --
  назва_моніторингу : VARCHAR(100)
  статус : VARCHAR(30)
  дата_встановлення : DATE
  частота_збору_даних : INTERVAL
  (FK) user_id : INTEGER
}

entity "МоніторингТемператури" as tempMon {
  (PK) temp_monitoring_id : INTEGER
  --
  нижня_межа : NUMERIC(5,2)
  верхня_межа : NUMERIC(5,2)
  (FK) monitoring_id : INTEGER
}

entity "МоніторингБезпеки" as secMon {
  (PK) security_monitoring_id : INTEGER
  --
  пріоритет_ризиків : VARCHAR(30)
  типи_ризику : VARCHAR(50)
  (FK) monitoring_id : INTEGER
}

entity "ПоточнаТемпература" as currTemp {
  (PK) curr_temp_id : INTEGER
  --
  значення : NUMERIC(5,2)
  останнє_оновлення : TIMESTAMP
  (FK) temp_monitoring_id : INTEGER
}

entity "ПоточнийСтанБезпеки" as currSec {
  (PK) curr_sec_id : INTEGER
  --
  загальний_статус : VARCHAR(30)
  останнє_оновлення : TIMESTAMP
  (FK) security_monitoring_id : INTEGER
}

entity "Сповіщення" as notif {
  (PK) notif_id : INTEGER
  --
  повідомлення : VARCHAR(255)
  дата_і_час : TIMESTAMP
  категорія_події : VARCHAR(50)
  (FK) monitoring_id : INTEGER
  (FK) user_id : INTEGER
}

entity "Датчик" as sensor {
  (PK) sensor_id : INTEGER
  --
  назва : VARCHAR(50)
  тип : VARCHAR(30)
  виробник : VARCHAR(50)
  модель : VARCHAR(50)
  (FK) location_id : INTEGER
  (FK) monitoring_id : INTEGER
}

entity "Локація" as location {
  (PK) location_id : SERIAL
  --
  назва_локації : VARCHAR(50)
  тип_локації : VARCHAR(30)
  будівля : VARCHAR(50)
  поверх : INTEGER
}

' --- Зв’язки ---
user ||--o{ monitoring : створює
monitoring ||--|{ tempMon
monitoring ||--|{ secMon
tempMon ||--|| currTemp : містить
secMon ||--|| currSec : містить
monitoring ||--|{ sensor : використовує
location ||--o{ sensor : містить
monitoring ||--o{ notif : генерує
user ||--o{ notif : отримує

@enduml
